name: Release

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - alpha/*
      - beta/*
      - stable/*
      - master

jobs:
  # Step 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  # Step 2: Semantic Release
  semantic-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Set NPM_PUBLISH for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "NPM_PUBLISH=true" >> $GITHUB_ENV

      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PUBLISH: ${{ env.NPM_PUBLISH || 'false' }}
        run:  npx semantic-release

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: semantic-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: login
        run: npm adduser

      - name: Publish to npm
        if: github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/beta' && env.NPM_PUBLISH == 'true')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PUBLISH: ${{ env.NPM_PUBLISH }}
        run: npm publish

  
