name: Semantic Version Update

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - alpha/*
      - beta/*
      - stable/*
      - master

jobs:
  # Step 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  semantic-version-update:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update semantic version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:semver

  npm-publish:
    runs-on: ubuntu-latest
    needs: semantic-version-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PUBLISH: ${{ github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/beta' && env.NPM_PUBLISH == 'true') }}
        run: npm run release:npm

  post-to-twitter:
    runs-on: ubuntu-latest
    needs: semantic-version-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Extract first change log entry
        id: extract_change_log
        run: |
          FIRST_ENTRY=$(awk '/^\* \*\*/{print; exit}' CHANGELOG.md)
          echo "CHANGELOG_ENTRY=${FIRST_ENTRY}" >> $GITHUB_ENV

      - name: Post to Twitter
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{'New release is available! Check it out.' }}"
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  
  