name: Semantic Version Update

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - alpha/*
      - beta/*
      - stable/*
      - master

jobs:
  # Step 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  semantic-version-update:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update semantic version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:semver

  npm-publish:
    runs-on: ubuntu-latest
    needs: semantic-version-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PUBLISH: ${{ github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/beta' && env.NPM_PUBLISH == 'true') }}
        run: npm run release:npm

  post-to-twitter:
    runs-on: ubuntu-latest
    needs: semantic-version-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Extract latest changelog entry
        id: extract_changelog
        run: |
          LATEST_CHANGELOG=$(awk '/^## \[/{if(NR!=1) exit; print;flag=1; next} /^#/{flag=0} flag' CHANGELOG.md)
          echo "LATEST_CHANGELOG=$LATEST_CHANGELOG" >> $GITHUB_ENV

      - name: Post to Twitter
        run: |
          curl -X POST "https://api.twitter.com/2/tweets" \
          -H "Authorization: Bearer ${{ secrets.TWITTER_BEARER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"text\":\"Latest Release: ${{ 'test' }}\"}"

  
  