name: Semantic Version Update

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - alpha/*
      - beta/*
      - stable/*
      - master

jobs:
  # Step 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  semantic-version-update:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update semantic version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:semver

  npm-publish:
    runs-on: ubuntu-latest
    needs: semantic-version-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PUBLISH: ${{ github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/beta' && env.NPM_PUBLISH == 'true') }}
        run: npm run release:npm

  post-to-twitter:
    runs-on: ubuntu-latest
    needs: semantic-version-update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Extract latest changelog entry
        id: extract_changelog
        run: |
          LATEST_CHANGELOG=$(awk '/^## \[/{if(NR!=1) exit; print;flag=1; next} /^#/{flag=0} flag' CHANGELOG.md)
          echo "LATEST_CHANGELOG=$LATEST_CHANGELOG" >> $GITHUB_ENV

      - name: Post to Twitter using OAuth 1.0a
        run: |
          oauth_signature=$(oauth_sign \
            --method POST \
            --url "https://api.twitter.com/2/tweets" \
            --consumer_key "${{ secrets.TWITTER_CONSUMER_KEY }}" \
            --consumer_secret "${{ secrets.TWITTER_CONSUMER_SECRET }}" \
            --token "${{ secrets.TWITTER_ACCESS_TOKEN }}" \
            --token_secret "${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" \
            --parameters "status=New Release: ${{ 'test' }}" \
            --base64)
          curl -X POST "https://api.twitter.com/2/tweets" \
            -H "Authorization: OAuth $oauth_signature" \
            -d "{\"status\":\"New Release: ${{ 'test 2' }}\"}"

  
  